sample_proj/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'all_articles' => 'articles#all'
  patch 'articles/:id', to: 'articles#update'
  root 'welcome#index'
  get 'all_admin' => 'articles#all_admin'
  get 'add_manager_to_user' => 'managers#choose'
  post 'add_manager_to_user' => 'managers#assign'
  post 'assign_manager_to_user' => 'managers#assign'
  get 'show_users' => 'managers#show_users'
  resources :articles do
    get 'add_comment/:id', action: 'add_comment'
    resources :comments
  end
  resources :tasks do
    collection do
      post '/destroy_all', to: 'tasks#destroy_all', as: 'destroy_all'
    end
    resources :employee_comments
  end
  get 'new_self_task' => 'tasks#self_task'
  get 'all_tasks' => 'tasks#all_tasks'
  post 'new_self_task' => 'tasks#create'
  post '/send_mail/:id', to: 'tasks#send_mail', as: 'send_mail'
  post '/archive/:id', to: 'tasks#archive', as: 'archive'
  post '/unarchive/:id', to: 'tasks#unarchive', as: 'unarchive'
  get '/archived_tasks', to: 'tasks#archived_tasks', as: 'archived_tasks'
  get 'view_admin_analytics' => 'analytics#view_admin'
  get 'view_manager_analytics' => 'analytics#view_manager'
  get 'view_employee_analytics' => 'analytics#view_employee'
  post 'get_months' => 'analytics#get_months'
  #get '/tasks/:id', to: 'tasks#send_mail', as: 'send_mail'
  #patch '/tasks/:id', to: 'tasks#send_mail', as: 'send_mail'
  # put '/tasks/:id', to: 'tasks#send_mail', as: 'send_mail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sample_proj/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    SendDeadlineExpiryMailJob.perform_now
  end
end

sample_proj/app/helpers/welcome_helper.rb
module WelcomeHelper
  def check_for_user_role(c_user)
    if c_user.role == Role.find_by_name('admin') and !c_user.admin.present?
      c_user.admin = true 
      c_user.manager_bool = false
      c_user.save
      render 'welcome/admin_login'
    elsif c_user.role == Role.find_by_name('manager') and !c_user.manager_bool.present?
      c_user.admin = false
      c_user.manager_bool = true
      c_user.save
      @manager = Manager.new
      @manager.email = c_user.email
      @manager.username = c_user.username
      @manager.firstname = c_user.firstname 
      @manager.lastname = c_user.lastname
      @manager.save
      render 'welcome/manager_login'
    elsif c_user.admin?
      render 'welcome/admin_login'
    elsif c_user.manager_bool?
      render 'welcome/manager_login'
    else
      render 'welcome/login'
    end
  end

  def send_deadline_expired_mail
    t = Time.now
    Task.where("is_completed = ? AND is_incomplete = ?", false, false).each do |task|
      if(t > task.due_date)
        @user = User.find(task.assignee_id)
        task.is_incomplete = true
        if task.save!
          TaskMailer.task_deadline_expired_mail(@user, task).deliver_now
          #'Deadline Expiry mails sent'
        end
      end
    end
  end
end

sample_proj/app/views/welcome/_admin_login.html.erb
<h4>Welcome Admin <%= current_user.username if current_user %></h4>
<p>
  <%= link_to 'New Self Task', new_self_task_path(:assignee_id => current_user.id)%><br>
  <%= link_to 'New User Task', new_task_path%><br>
  <%= link_to 'All Admin Tasks', tasks_path%><br>
  <%= link_to 'Assign Manager to User', add_manager_to_user_path%><br>
  <%= link_to 'All Tasks', all_tasks_path%><br>
  <%= link_to 'Archived Tasks', archived_tasks_path %><br>
  <%= link_to 'View Analytics', view_admin_analytics_path %>
</p>

sample_proj/app/views/welcome/_login.html.erb
<h4>Welcome <%= current_user.username if current_user %></h4>
<p>
<%= link_to 'View Tasks', tasks_path%><br>
<%= link_to 'View Analytics', view_employee_analytics_path %>
</p>

sample_proj/app/views/welcome/_manager_login.html.erb
<h4>Welcome Manager <%= current_user.username if current_user %></h4>
<p>
  <%= link_to 'New Self Task', new_self_task_path(:assignee_id => current_user.id)%><br>
  <%= link_to 'New User Task', new_task_path%><br>
  <%= link_to 'All Tasks', tasks_path%><br>
  <%= link_to 'All Users', show_users_path %><br>
  <%= link_to 'Archived Tasks', archived_tasks_path %><br>
  <%= link_to 'View Analytics', view_manager_analytics_path %>
</p>

sample_proj/app/views/welcome/index.html.erb
<h1>Welcome to Task Creator</h1>
<% #send_deadline_expired_mail %>
<% if user_signed_in? %>
    <%= check_for_user_role current_user %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %><br>
<% else %>
    <%= link_to 'Sign In', new_user_session_path %><br>
    <%= link_to 'Sign Up', new_user_registration_path %><br>
<% end %>