sample_proj/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'all_articles' => 'articles#all'
  patch 'articles/:id', to: 'articles#update'
  root 'welcome#index'
  get 'all_admin' => 'articles#all_admin'
  get 'add_manager_to_user' => 'managers#choose'
  post 'add_manager_to_user' => 'managers#assign'
  post 'assign_manager_to_user' => 'managers#assign'
  get 'show_users' => 'managers#show_users'
  resources :articles do
    get 'add_comment/:id', action: 'add_comment'
    resources :comments
  end
  resources :tasks do
    collection do
      post '/destroy_all', to: 'tasks#destroy_all', as: 'destroy_all'
    end
    resources :employee_comments
  end
  get 'new_self_task' => 'tasks#self_task'
  get 'all_tasks' => 'tasks#all_tasks'
  post 'new_self_task' => 'tasks#create'
  post '/send_mail/:id', to: 'tasks#send_mail', as: 'send_mail'
  post '/archive/:id', to: 'tasks#archive', as: 'archive'
  post '/unarchive/:id', to: 'tasks#unarchive', as: 'unarchive'
  get '/archived_tasks', to: 'tasks#archived_tasks', as: 'archived_tasks'
  get 'view_admin_analytics' => 'analytics#view_admin'
  get 'view_manager_analytics' => 'analytics#view_manager'
  get 'view_employee_analytics' => 'analytics#view_employee'
  post 'get_months' => 'analytics#get_months'
  #get '/tasks/:id', to: 'tasks#send_mail', as: 'send_mail'
  #patch '/tasks/:id', to: 'tasks#send_mail', as: 'send_mail'
  # put '/tasks/:id', to: 'tasks#send_mail', as: 'send_mail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sample_proj/app/models/manager.rb
class Manager < ApplicationRecord
  has_many :users
  validates_presence_of :email, :username
end

sample_proj/app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :authenticate_user!
  def choose

  end
  def assign
    @manager = Manager.find(params[:manager][:manager_id])
    @user = User.find(params[:user][:user_id])
    @prev_manager = @user.manager
    @manager.users << @user
    @user_man = User.find_by_username @manager.username
    @tasks = Task.where("user_id = ? AND assignee_id = ? AND is_completed = ? AND is_incomplete = ?", @manager.id, @user.id, false, false)
    @tasks.each do |task|
      task.user = @user_man
      task.save
    end
    redirect_to welcome_index_path
  end
  def show_users
    @manager = Manager.find_by_username current_user.username
  end

  private

end

sample_proj/app/helpers/managers_helper.rb
module ManagersHelper
end

sample_proj/app/views/managers/choose.html.erb
<%= form_tag(use_route: assign_manager_to_user_path, method: 'post') do %>
    <p>
      <strong>Manager:</strong>
      <%= collection_select :manager, :manager_id, Manager.all, :id, :username %>
    </p>
    <p>
      <strong>User:</strong>
      <%= collection_select :user, :user_id, User.where(admin: false, manager_bool: false), :id, :username %>
    </p>
    <%= submit_tag('Assign') %>
<% end %>

sample_proj/app/views/managers/show_users.html.erb
<table>
  <tr>
    <th>User Name</th>
    <th>First name</th>
    <th>Last name</th>
    <th colspan="3"></th>
  </tr>
  <% if current_user.present? %>
      <% @manager.users.all.each do |user| %>
          <tr>
            <td><%= user.username %></td>
            <td><%= user.firstname %></td>
            <td><%= user.lastname %></td>
          </tr>
      <% end %>
  <% end %>
</table>