sample_proj/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'all_articles' => 'articles#all'
  patch 'articles/:id', to: 'articles#update'
  root 'welcome#index'
  get 'all_admin' => 'articles#all_admin'
  get 'add_manager_to_user' => 'managers#choose'
  post 'add_manager_to_user' => 'managers#assign'
  post 'assign_manager_to_user' => 'managers#assign'
  get 'show_users' => 'managers#show_users'
  resources :articles do
    get 'add_comment/:id', action: 'add_comment'
    resources :comments
  end
  resources :tasks do
    collection do
      post '/destroy_all', to: 'tasks#destroy_all', as: 'destroy_all'
    end
    resources :employee_comments
  end
  get 'new_self_task' => 'tasks#self_task'
  get 'all_tasks' => 'tasks#all_tasks'
  post 'new_self_task' => 'tasks#create'
  post '/send_mail/:id', to: 'tasks#send_mail', as: 'send_mail'
  post '/archive/:id', to: 'tasks#archive', as: 'archive'
  post '/unarchive/:id', to: 'tasks#unarchive', as: 'unarchive'
  get '/archived_tasks', to: 'tasks#archived_tasks', as: 'archived_tasks'
  get 'view_admin_analytics' => 'analytics#view_admin'
  get 'view_manager_analytics' => 'analytics#view_manager'
  get 'view_employee_analytics' => 'analytics#view_employee'
  post 'get_months' => 'analytics#get_months'
  #get '/tasks/:id', to: 'tasks#send_mail', as: 'send_mail'
  #patch '/tasks/:id', to: 'tasks#send_mail', as: 'send_mail'
  # put '/tasks/:id', to: 'tasks#send_mail', as: 'send_mail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sample_proj/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

sample_proj/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = current_user.articles.all
  end

  def all
    @articles = Article.all
  end

  def all_admin
    @articles = Article.all
  end

  def add_comment
    respond_to do |format|
      format.js
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      flash[:alert] = "Article Created!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy

    @article = Article.find(params[:id])
    @article.destroy
    flash[:alert] = "Article Destroyed!"
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

sample_proj/app/helpers/articles_helper.rb
module ArticlesHelper
end

sample_proj/app/views/articles/_edit_form.html.erb
<%= form_for @article, url: article_path(@article), html: {method: 'patch'} do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

sample_proj/app/views/articles/_form.html.erb
<%= form_for @article, url: articles_path do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

sample_proj/app/views/articles/add_comment.html.erb
<div id = "1">
</div>

sample_proj/app/views/articles/add_comment.js.erb
$('#1').html("<%= render :partial => 'comments/new' %>");

sample_proj/app/views/articles/all.html.erb
<%= link_to 'New article', new_article_path %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
  </tr>
  <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <% if current_user == article.user %>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <% end %>
      </tr>
  <% end %>
</table>
<%= link_to 'Back', root_path%>

sample_proj/app/views/articles/all_admin.html.erb
<%= link_to 'New article', new_article_path %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
  </tr>
  <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td>
        <% if current_user == article.user%>
          <%= link_to 'Edit', edit_article_path(article) %>
        <% end %>
        </td>
        <td><%= link_to 'Destroy', article_path(article),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>
<%= link_to 'Back', root_path%>

sample_proj/app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'edit_form' %>
<%= link_to 'Back', articles_path %>

sample_proj/app/views/articles/index.html.erb
<%= link_to 'New article', new_article_path %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
  </tr>
  <% if current_user.present? %>
    <% @articles.each do |article| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.body %></td>
          <td><%= link_to 'Show', article_path(article) %></td>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <% if current_user.admin? %>
          <td><%= link_to 'Destroy', article_path(article),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
    <% end %>
  <% end %>
</table>
<%= link_to 'Back', root_path%>

sample_proj/app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

sample_proj/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.user.email%>
</p>

<p>
  <strong> Comments </strong>
  <% @article.comments.all.each do |comment|%>
    <p>
      <strong>Author:</strong><br>
      <%= comment.user.email%><br>
      <strong>Comment:</strong><br>
      <%= comment.comment %><br>
      <% if comment.user == current_user%>
        <%= link_to 'Delete', article_comment_path(@article, comment),
                    method: :delete,
                    data: {confirm: 'Are you sure?'} %>
      <% end %>
    </p>
  <% end %>
</p>

<p>
  <%=render 'comments/new' %>
</p>

<%= link_to 'Back', articles_path %>